import Head from "next/head";
import { FC } from "react";
import Footer from "../Footer/Footer";
import UnderConstruction from "../UnderConstruction/UnderConstruction";
import styles from './Layout.module.css';

interface Props {
  children: React.ReactNode;
}

const Layout:FC<Props> = ({children}) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div>
        <UnderConstruction/>
        {/* TODO: NAV */}
      </div>
      <div className={styles.contentGroup}>
        {children}
      </div>
      <div>
        <Footer/>
      </div>
    </div>
  );
}

export default Layout;
